/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DATA.AbrirImagen;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Roberto Cruz Leija
 */
public class JFrameImagenPaleta extends javax.swing.JFrame {

    /**
     * Creates new form JFrameImagenPaleta
     */
    public JFrameImagenPaleta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelImagenO = new javax.swing.JPanel();
        jLabelImagenOriginal = new javax.swing.JLabel();
        jPanelIGrises = new javax.swing.JPanel();
        jPanelHistograma = new javax.swing.JPanel();
        jPanelRojos = new javax.swing.JPanel();
        jPanelVerdes = new javax.swing.JPanel();
        Azules = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButtonAbrirImagen = new javax.swing.JButton();
        jButtonGrisesH = new javax.swing.JButton();
        jButtonRGB = new javax.swing.JButton();
        jButtonWeb = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Práctica Imagenes");

        javax.swing.GroupLayout jPanelImagenOLayout = new javax.swing.GroupLayout(jPanelImagenO);
        jPanelImagenO.setLayout(jPanelImagenOLayout);
        jPanelImagenOLayout.setHorizontalGroup(
            jPanelImagenOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelImagenOLayout.createSequentialGroup()
                .addComponent(jLabelImagenOriginal)
                .addGap(0, 1462, Short.MAX_VALUE))
        );
        jPanelImagenOLayout.setVerticalGroup(
            jPanelImagenOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelImagenOLayout.createSequentialGroup()
                .addComponent(jLabelImagenOriginal)
                .addGap(0, 746, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Imagen Original", jPanelImagenO);

        javax.swing.GroupLayout jPanelIGrisesLayout = new javax.swing.GroupLayout(jPanelIGrises);
        jPanelIGrises.setLayout(jPanelIGrisesLayout);
        jPanelIGrisesLayout.setHorizontalGroup(
            jPanelIGrisesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1462, Short.MAX_VALUE)
        );
        jPanelIGrisesLayout.setVerticalGroup(
            jPanelIGrisesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 746, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Imagen Grises", jPanelIGrises);

        javax.swing.GroupLayout jPanelHistogramaLayout = new javax.swing.GroupLayout(jPanelHistograma);
        jPanelHistograma.setLayout(jPanelHistogramaLayout);
        jPanelHistogramaLayout.setHorizontalGroup(
            jPanelHistogramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1462, Short.MAX_VALUE)
        );
        jPanelHistogramaLayout.setVerticalGroup(
            jPanelHistogramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 746, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Histograma", jPanelHistograma);

        javax.swing.GroupLayout jPanelRojosLayout = new javax.swing.GroupLayout(jPanelRojos);
        jPanelRojos.setLayout(jPanelRojosLayout);
        jPanelRojosLayout.setHorizontalGroup(
            jPanelRojosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1462, Short.MAX_VALUE)
        );
        jPanelRojosLayout.setVerticalGroup(
            jPanelRojosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 746, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Rojos", jPanelRojos);

        javax.swing.GroupLayout jPanelVerdesLayout = new javax.swing.GroupLayout(jPanelVerdes);
        jPanelVerdes.setLayout(jPanelVerdesLayout);
        jPanelVerdesLayout.setHorizontalGroup(
            jPanelVerdesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1462, Short.MAX_VALUE)
        );
        jPanelVerdesLayout.setVerticalGroup(
            jPanelVerdesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 746, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Verdes", jPanelVerdes);

        javax.swing.GroupLayout AzulesLayout = new javax.swing.GroupLayout(Azules);
        Azules.setLayout(AzulesLayout);
        AzulesLayout.setHorizontalGroup(
            AzulesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1462, Short.MAX_VALUE)
        );
        AzulesLayout.setVerticalGroup(
            AzulesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 746, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Azules", Azules);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1462, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 746, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Camara Web", jPanel1);

        jButtonAbrirImagen.setText("Abrir Imagen");
        jButtonAbrirImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbrirImagenActionPerformed(evt);
            }
        });

        jButtonGrisesH.setText("Grises e Histograma");

        jButtonRGB.setText("Rojos/Verdes/Azules");

        jButtonWeb.setText("Captura Web");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jButtonAbrirImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonGrisesH, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonRGB, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 793, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonAbrirImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(jButtonGrisesH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonRGB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonWeb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAbrirImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbrirImagenActionPerformed
        // Abrir la imagen original 
        // y mandarla como icono al label
        Image imagenOriginal = AbrirImagen.abrir();
        this.jLabelImagenOriginal.setIcon(new ImageIcon(imagenOriginal));
    }//GEN-LAST:event_jButtonAbrirImagenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameImagenPaleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameImagenPaleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameImagenPaleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameImagenPaleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameImagenPaleta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Azules;
    private javax.swing.JButton jButtonAbrirImagen;
    private javax.swing.JButton jButtonGrisesH;
    private javax.swing.JButton jButtonRGB;
    private javax.swing.JButton jButtonWeb;
    private javax.swing.JLabel jLabelImagenOriginal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelHistograma;
    private javax.swing.JPanel jPanelIGrises;
    private javax.swing.JPanel jPanelImagenO;
    private javax.swing.JPanel jPanelRojos;
    private javax.swing.JPanel jPanelVerdes;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
